### ISSUE TITLE
Implement basic Stack and its functions  

### ISSUE THREAD

**Issue by Manvityagi** [Manvityagi/Data-Structures-and-Algorithms#14]
- Create Stack folder in DS implementation and add a code file there. 
- Do corresponding additions in the documentation.
- Comment your code where necessary.

**Comment by urvashi-code1255** [comment]
I will work on this. Please assign me this.

**Comment by Manvityagi** [comment]
> I will work on this. Please assign me this.

Assigned to you @urvashi-code1255
