### ISSUE TITLE
Segment Trees is not accessible through Data Structures Implementation 

### ISSUE THREAD

**Issue by Mirnal1409** [Manvityagi/Data-Structures-and-Algorithms#39]
Segment Trees code page is not accessible when one goes through Data Structures implementation and click on Segment Trees. It is redirecting to Fenwick Trees.

![Screenshot (1191)](https://user-images.githubusercontent.com/30199522/96543582-4ecdd600-12c2-11eb-96cf-461856bd83ae.png)

**Comment by Manvityagi** [comment]
You may send a PR for solving that @Mirnal1409.

**Comment by Mirnal1409** [comment]
ok
